// src/ui/solidjs/playground.tsx
/** @jsxImportSource solid-js */

import type { JSXElement } from 'solid-js'
import { cn } from 'utils/helpers'

export default function Playground(props: {
  class?: string
  aspectRatio?: string
  overflow?: string
  children: JSXElement
}) {
  return (
    <div
      class={cn(
        'bg-slate-950 bg-[image:radial-gradient(circle_at_1px_1px,_#1e283b_1px,_transparent_0)] bg-[size:20px_20px] bg-[position:8px_8px]',
        'relative rounded-xl border border-slate-400/20',
        'overflow-hidden',
        'aspect-[1/1] sm:aspect-[4/3] md:aspect-[10/6]',
        props.class,
      )}
    >
      {props.children}
    </div>
  )
}

// src/ui/react/playground.tsx
type Props = {
  children: React.ReactNode
  description?: string
}

export function Playground({ children, description }: Props) {
  return (
    <div className="bg-slate-800 bg-[image:radial-gradient(circle_at_1px_1px,_#475569_1px,_transparent_0)] bg-[size:20px_20px] bg-[position:10px_16px] p-4">
      <div className="flex items-center justify-center">
        <span className="text-white">component here</span>
      </div>
    </div>
  )
}
